version: "3.3"

services:
  tienda:
    image: postgres:13
    container_name: tienda
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=paula
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    container_name: mysql
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    ports:
      - 8080:80

  app:
    image: node:18
    container_name: app
    command: npm run dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DB_USER=paula
      - DB_PASSWORD=123456
      - DB_HOST=tienda
      - DB_PORT=5432
      - DB_NAME=my_store
    depends_on:
      - tienda
